Tests: Bugfix: Repair broken tests
- random.sample() (no longer) allows 'set' type, so convert to list.

  - From error message:

      TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).